elao_enum:
    # Provide the enum classes for which you want to automatically generate & register Doctrine DBAL Types:
    # https://github.com/Elao/PhpEnums#doctrine
    doctrine:
        types:
            homeoffice: App\Enum\HomeOfficeEnum
            oeffi_erreichbarkeit: App\Enum\OeffiErreichbarkeitEnum
            slack_time: App\Enum\SlackTimeEnum